[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200   
upload_port = COM3        ; ← add this
monitor_port = COM3  

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  miguelbalboa/MFRC522
  knolleary/PubSubClient
  adafruit/Adafruit NeoPixel
